// import 'package:flutter/foundation.dart';
import 'package:library_app/models/book.dart';
import 'models/category.dart';

final Categories_data = const [
  Category(
    id: 'c1',
    title: 'Science',
    imageUrl: 'assets/images/science.jpg',
  ),
  Category(
    id: 'c2',
    title: 'History',
    imageUrl: 'assets/images/History.jpg',
  ),
  Category(
    id: 'c3',
    title: 'Mathematics',
    imageUrl: 'assets/images/math-cover-book.jpeg',
  ),
  Category(
    id: 'c4',
    title: 'Literature',
    imageUrl: 'assets/images/Literature-cover-book.jpeg',
  ),
  Category(
    id: 'c5',
    title: 'Technology',
    imageUrl: 'assets/images/technology.jpg',
  ),
  Category(
    id: 'c6',
    title: 'Art',
    imageUrl: 'assets/images/Art-cover-book1.jpg',
  ),
];
//      #######################################
final books_data = const [
  Book(
    id: 'b1',
    title: 'History-1',
    imageUrl:  'assets/images/History.jpg',
    categories: ['c2'],
    pageNumbers: 201,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b2',
    title: 'History-2',
    imageUrl:  'assets/images/History.jpg',
    categories: ['c2'],
    pageNumbers: 312,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b3',
    title: 'History-3',
    imageUrl:  'assets/images/History.jpg',
    categories: ['c2'],
    pageNumbers: 334,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b4',
    title: 'History-4',
    imageUrl: 'assets/images/History.jpg',
    categories: ['c2'],
    pageNumbers: 523,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl:'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b5',
    title: 'Science-1',
    imageUrl: 'assets/images/science.jpg',
    categories: ['c1'],
    pageNumbers: 56,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b6',
    title: 'Science-2',
    imageUrl: 'assets/images/science.jpg',
    categories: ['c1'],
    pageNumbers: 233,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b7',
    title: 'Science-3',
    imageUrl:'assets/images/science.jpg',
    categories: ['c1'],
    pageNumbers: 36,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b8',
    title: 'Science-4',
    imageUrl: 'assets/images/science.jpg',
    categories: ['c1'],
    pageNumbers: 546,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b9',
    title: 'Literiture-1',
    imageUrl: 'assets/images/Literature-cover-book.jpeg',
    categories: ['c4'],
    pageNumbers: 243,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b10',
    title: 'Literiture-2',
    imageUrl: 'assets/images/Literature-cover-book.jpeg',
    categories: ['c4'],
    pageNumbers: 123,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b11',
    title: 'Literiture-3',
    imageUrl: 'assets/images/Literature-cover-book.jpeg',
    categories: ['c4'],
    pageNumbers: 234,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b12',
    title: 'Literiture-4',
    imageUrl: 'assets/images/Literature-cover-book.jpeg',
    categories: ['c4'],
    pageNumbers: 456,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b13',
    title: 'Math-1',
    imageUrl: 'assets/images/math-cover-book.jpeg',
    categories: ['c3'],
    pageNumbers: 123,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b14',
    title: 'Math-2',
    imageUrl: 'assets/images/math-cover-book.jpeg',
    categories: ['c3'],
    pageNumbers: 456,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b15',
    title: 'Math-3',
    imageUrl: 'assets/images/math-cover-book.jpeg',
    categories: ['c3'],
    pageNumbers: 789,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b16',
    title: 'Math-4',
    imageUrl: 'assets/images/math-cover-book.jpeg',
    categories: ['c3'],
    pageNumbers: 123,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b17',
    title: 'Art-1',
    imageUrl: 'assets/images/Art-cover-book1.jpg',
    categories: ['c6'],
    pageNumbers: 123,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b18',
    title: 'Art-2',
    imageUrl: 'assets/images/Art-cover-book1.jpg',
    categories: ['c6'],
    pageNumbers: 456,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b19',
    title: 'Art-3',
    imageUrl: 'assets/images/Art-cover-book1.jpg',
    categories: ['c6'],
    pageNumbers: 789,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b20',
    title: 'Art-4',
    imageUrl: 'assets/images/Art-cover-book1.jpg',
    categories: ['c6'],
    pageNumbers: 123,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b21',
    title: 'Technology-1',
    imageUrl: 'assets/images/technology.jpg',
    categories: ['c5'],
    pageNumbers: 123,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b22',
    title: 'Technology-2',
    imageUrl: 'assets/images/technology.jpg',
    categories: ['c5'],
    pageNumbers: 456,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b23',
    title: 'Technology-3',
    imageUrl: 'assets/images/technology.jpg',
    categories: ['c5'],
    pageNumbers: 789,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
  Book(
    id: 'b24',
    title: 'Technology-4',
    imageUrl: 'assets/images/technology.jpg',
    categories: ['c5'],
    pageNumbers: 123,
    author: 'Muhammed El-sayed',
    bookDetails: [
      "lorem ipsum dolor sit amet",
      "consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
      "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    ],
    pdfUrl: 'assets/docs/1st Python session.pdf',
  ),
];
